- name: Manage Google Cloud Run service
  collections:
      - community.general
      - community.general.gcp_cloud_run_service
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Ensure a Cloud Run service is present
        community.general.gcp_cloud_run_service:
            name: 'hephaestus-api'
            location: 'us-west1'
            template:
                spec:
                    containers:
                        - image: 'gcr.io/hephaestus-418809/hephaestus-api:latest'
            autogenerate_revision_name: true
            state: present
            project: hephaestus-418809
            auth_kind: serviceaccount
            service_account_file: '/terraform/hephaestus-418809-ba3b07f622bf.json'
