- name: Manage Google Cloud Run service
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Ensure a Cloud Run service is present
        community.general.gcp_cloud_run_service:
            name: 'example-service'
            location: 'us-central1'
            template:
                spec:
                    containers:
                        - image: 'gcr.io/your-project-id/example-image'
            autogenerate_revision_name: true
            state: present
            project: your-project-id
            auth_kind: serviceaccount
            service_account_file: '/path/to/your-service-account-file.json'
