- name: Deploy Docker image to Google Cloud Run using gcloud CLI
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Authenticate gcloud with a service account
      ansible.builtin.shell: |
        gcloud auth activate-service-account --key-file=/home/milheht/src/hephaestus-api/terraform/hephaestus-418809-aca9086bcf82.json
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/home/milheht/src/hephaestus-api/terraform/hephaestus-418809-aca9086bcf82.json"

    - name: Deploy to Cloud Run using gcloud
      ansible.builtin.command:
        cmd: gcloud run deploy hephaestus-api --image=gcr.io/hephaestus-418809/hephaestus-api:latest --region=us-west1 --platform=managed --allow-unauthenticated --project=hephaestus-418809
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/home/milheht/src/hephaestus-api/terraform/hephaestus-418809-aca9086bcf82.json"
