- name: Deploy Docker image to Google Cloud Run using gcloud CLI
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Configure Docker to use gcloud as a credential helper
        ansible.builtin.shell: |
            gcloud auth configure-docker --quiet

      - name: Authenticate gcloud with a service account
        ansible.builtin.shell: |
            gcloud auth activate-service-account --key-file={{ playbook_dir }}/terraform/hephaestus-418809-aca9086bcf82.json
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ playbook_dir }}/terraform/hephaestus-418809-aca9086bcf82.json'

      - name: Build latest docker
        ansible.builtin.shell:
            cmd: docker build -t gcr.io/hephaestus-418809/hephaestus-api:latest .
        environment:
            DOCKER_BUILDKIT: 1

      - name: Push latest docker
        ansible.builtin.shell:
            cmd: docker push gcr.io/hephaestus-418809/hephaestus-api:latest
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ playbook_dir }}/terraform/hephaestus-418809-aca9086bcf82.json'

      - name: Deploy to Cloud Run using gcloud
        ansible.builtin.command:
            cmd: gcloud run deploy hephaestus-api --image=gcr.io/hephaestus-418809/hephaestus-api:latest --region=us-west1 --platform=managed --allow-unauthenticated --project=hephaestus-418809 --add-cloudsql-instances hephaestus-418809:us-west1:hephaestus-postgres
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ playbook_dir }}/terraform/hephaestus-418809-aca9086bcf82.json'

      - name: Enable unauthenticated calls
        ansible.builtin.command:
            cmd: gcloud run services add-iam-policy-binding hephaestus-api --member="allUsers" --role="roles/run.invoker" --region=us-west1
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ playbook_dir }}/terraform/hephaestus-418809-aca9086bcf82.json'
