- name: Deploy Docker image to Google Cloud Run using gcloud CLI
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Find the service account key file
        ansible.builtin.find:
            paths: '{{ playbook_dir }}/terraform'
            patterns: 'hephaestus-418809-*.json'
        register: key_file

      - name: Fail if no key file is found
        ansible.builtin.fail:
            msg: 'No service account key file found'
        when: key_file.matched == 0

      - name: Set the key file path
        set_fact:
            key_file_path: '{{ key_file.files[0].path }}'
        when: key_file.matched > 0

      - name: Configure Docker to use gcloud as a credential helper
        ansible.builtin.shell: |
            gcloud auth configure-docker --quiet

      - name: Authenticate gcloud with a service account
        ansible.builtin.shell: |
            gcloud auth activate-service-account --key-file={{ key_file_path }}
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ key_file_path }}'

      - name: Build latest docker
        ansible.builtin.shell:
            cmd: docker build -t gcr.io/hephaestus-418809/hephaestus-api:latest .
        environment:
            DOCKER_BUILDKIT: 1

      - name: Push latest docker
        ansible.builtin.shell:
            cmd: docker push gcr.io/hephaestus-418809/hephaestus-api:latest
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ key_file_path }}'

      - name: Deploy to Cloud Run using gcloud
        ansible.builtin.command:
            cmd: gcloud run deploy hephaestus-api --image=gcr.io/hephaestus-418809/hephaestus-api:latest --region=us-west1 --platform=managed --allow-unauthenticated --project=hephaestus-418809 --add-cloudsql-instances hephaestus-418809:us-west1:user-api
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ key_file_path }}'

      - name: Enable unauthenticated calls
        ansible.builtin.command:
            cmd: gcloud run services add-iam-policy-binding hephaestus-api --member="allUsers" --role="roles/run.invoker" --region=us-west1
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: '{{ key_file_path }}'
