openapi: '3.0.2'
info:
  title: User API
  version: '1.0'
servers:
  - url: https://user-api.apigateway.com
paths:
  /user:
    post:
      summary: Create a user
      operationId: createUser
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/api
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /user/{id}:
    get:
      summary: Get a user
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/api
      security:
        - api_key: []
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal server error
    put:
      summary: Update a user
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/api
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/api
      security:
        - api_key: []
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
